# Generated by Django 6.0 on 2025-12-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("limpa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="episode_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
