# Generated by Django 6.0 on 2026-01-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("limpa", "0002_podcast_episode_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="last_refreshed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="processed_episodes",
            field=models.JSONField(default=dict),
        ),
    ]
