# Generated by Django 6.0 on 2026-01-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("limpa", "0003_add_processed_episodes_and_last_refreshed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
